### ISSUE TITLE
feat: Cleanup Gradle generated files (DSL in particular)

### ISSUE THREAD

**Issue by oSumAtrIX** [sigoden/projclean#34]
# Issue

While Gradle is supported, Gradle DSL is not. Gradle DSL is primarily used for development using Kotlin. Kotlin is primarily used for Android or Kotlin Multiplatform development. 

# Solution

The only difference between Gradle and Gradle DSL is the project file extension. Instead of `.gradle`, the project file ends with `.gradle.kts` which allows using Kotlin DSL for composing Gradle projects.

# Some repositories for reference

- https://github.com/revanced/revanced-patches/
- https://github.com/Aliucord/Aliucord
- https://github.com/kordlib/kord
- https://github.com/revanced/revanced-manager/
- https://github.com/MateriiApps/Gloom

**Comment by sigoden** [comment]
Is the `.gradle,build@build.gradle.kts` rule working? @oSumAtrIX

**Comment by oSumAtrIX** [comment]
Yes, I have used it manually
